server {
  listen 3000;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ $uri.html /index.html;
  }

  location ~* \.(css|gif|ico|jpg|jpeg|js|png|svg|webp|woff2?)$ {
    expires 1h;
    add_header Cache-Control "public";
    try_files $uri =404;
  }
}
